version: '3.8'
services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: collaboradocs
      MONGO_INITDB_ROOT_PASSWORD: collaboradocs
    ports:
      - '27017:27017'
    volumes:
      - 'mongo-data:/data/db:/dump'  # Corrected volume syntax
  collaboradocs:
    image: ahmedbelhaj2/collaboradocdocker
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  mongo-data:
